# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: ./application/src
      dockerfile: Dockerfile
    container_name: hive-app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./database/
    container_name: hive-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: hive
    ports:
      - "3306:3306"