# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: ./application/src
      dockerfile: Dockerfile
    container_name: hive-app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./database
    container_name: hive-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: hive
    ports:
      - "3306:3306"

  jenkins:
    build:
      context: ./jenkins
    container_name: hive-jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

volumes:
  jenkins_data: