# docker-compose.yml
version: '3'
services:
  app:
    build:
      dockerfile: application/Dockerfile
    container_name: hive-app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./database
    container_name: hive-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: hive-db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db