pipeline {
    agent { label '!windows' }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'docker-compose up --build -d'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Add your test commands here. For example:
                // sh 'docker-compose run --rm phpunit'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up...'
            sh 'docker-compose down'
        }
    }
}