pipeline {
    agent any

    stages {
//         stage('Install dependencies') {
//             agent { docker { image 'composer:2.6' } }
//             steps {
//                 sh 'composer install --ignore-platform-reqs'
//                 stash name: 'vendor', includes: 'vendor/**'
//             }
//         }
//         stage('Unit Tests') {
//             agent { docker { image 'php:8.0-apache' } }
//             steps {
//                 unstash name: 'vendor'
//             }
//         }
    }
}